### ISSUE TITLE
Homework 1 part 3 of Pablo Gonzalez

### ISSUE THREAD

**Issue by pgonzalez6** [pgonzalez6/stat679work#2]
Here is the exercise 3 of homework 1. I can complete all the variables required, less the variables under3460, under3450 and under34440. I can obtain the loglik numbers, however I'm having problems to run the for and IF function. I think that it is very closed to solve...I'll be working on this the rest of today. 

https://github.com/pgonzalez6/stat679work/commit/6a99426df05d62d270b1494dbefe130884ccd640
@cecileane

**Comment by cecileane** [comment]
Thanks Pablo! This is my way of asking Rebecca (@rebeccapost) and William (@mortonwilliam) to try your script and provide feedback on it. Thanks for your posting what you have so far, and for explaining where you are at.

If you have any update later today, please post a message on this thread to let Rebecca and William know that they should run `git pull origin master` to get your updates. Thanks to you all!

**Comment by pgonzalez6** [comment]
Hi Dr. @cecileane, 

finally I can find one solution...Reviewing the script of @anyezijue49 I found an easy way to generate the variables under3440,3450 and 3460, thanks so much! I hope you can check that the script works well and also make easier the way for those who will review it like @rebeccapost and @mortonwilliam. Regards, Pablo.

**Comment by rebeccapost** [comment]
I believe that your code could be more efficient if you used sed instead of grep because then you could avoid piping through multiple functions.
In addition, where you use sed to find the seed, you could do this in 1 sed call by using what we learned about capturing part of the line in () and then calling that with \1 in the replacement part of the sed call.

You should be able to complete the basename call without piping. I think "basename $i .log" should work to get the analysis name.

If possible, I would change the name of $i to something more descriptive like $file or $logfile just so that is clear what it is when it is being called later on the script.

You commented above that you found a solution for the last three variables, but just in case, I wanted to tell you my idea. I created a for loop that went through the loglik values and then within the for loop I used 3 if/then statements to increase the count of the under3440 and other variables.

Since this is a short script, not much documentation is needed, but you could add comments before some of the harder to understand variables to say what they are.

I liked that you echo'ed the variables all in one line at the end in order to check that you have collected the correct information.

You have a nice thorough comment about what you were unable to complete and how you had been approaching the problem, which makes it very easy for a collaborator (if you had one) to see what you were trying to do.

Overall your code is well written and easy to follow!

**Comment by mortonwilliam** [comment]
Hello Pablo, 

Your scripts are very concise and condensed, and although you have a few comments in with your script I think a few more would be helpful.  That would probably make it more user friendly. I also found the way you set up your “if-then” statements to be very interesting, and its nice to see a different way of doing it. 

In general, I think your code is well written making it easy to understand. 

GREAT JOB!
